from datetime import date, datetime, timedelta, timezone
from typing import Optional

from app.ingest.sources.base import LicenseSource


class SampleLicenseSource(LicenseSource):
    source_state = "TX"
    source_agency = "Texas Medical Board"
    license_type_codes = ("MD",)

    def fetch(self, since: Optional[date] = None) -> list[dict]:
        today = date.today()
        return [
            {
                "source_state": "TX",
                "source_agency": self.source_agency,
                "source_url": "https://www.tmb.texas.gov/page/look-up-a-license",
                "source_record_id": "sample-md-001",
                "license_number": "M12345",
                "license_type_code": "MD",
                "profession": "Physician",
                "specialty": "Dermatology",
                "full_name": "Jane A. Smith",
                "business_name": "Lone Star Dermatology",
                "status_raw": "Active",
                "issue_date": today.replace(year=today.year - 8),
                "expiration_date": today + timedelta(days=60),
                "address_city": "Austin",
                "address_state": "TX",
                "address_zip": "78701",
                "source_fetched_at": datetime.now(timezone.utc),
            },
            {
                "source_state": "FL",
                "source_agency": "Florida DBPR",
                "source_url": "https://www.myfloridalicense.com/wl11.asp",
                "source_record_id": "sample-gc-001",
                "license_number": "CGC1520001",
                "license_type_code": "GC",
                "profession": "General Contractor",
                "specialty": "Residential",
                "full_name": "Marcus Rivera",
                "business_name": "Rivera Coastal Builders",
                "status_raw": "Current Active",
                "issue_date": today.replace(year=today.year - 5),
                "expiration_date": today + timedelta(days=28),
                "address_city": "Tampa",
                "address_state": "FL",
                "address_zip": "33602",
                "source_fetched_at": datetime.now(timezone.utc),
            },
            {
                "source_state": "CA",
                "source_agency": "California DRE",
                "source_url": "https://www2.dre.ca.gov/PublicASP/pplinfo.asp",
                "source_record_id": "sample-re-001",
                "license_number": "02100001",
                "license_type_code": "RE_SALES",
                "profession": "Real Estate Salesperson",
                "specialty": "Residential Sales",
                "full_name": "Priya Chen",
                "business_name": "North Bay Realty",
                "status_raw": "Licensed",
                "issue_date": today.replace(year=today.year - 3),
                "expiration_date": today + timedelta(days=83),
                "address_city": "San Diego",
                "address_state": "CA",
                "address_zip": "92101",
                "source_fetched_at": datetime.now(timezone.utc),
            },
            {
                "source_state": "TX",
                "source_agency": "Texas Board of Nursing",
                "source_url": "https://www.bon.texas.gov/licensure_verification.asp",
                "source_record_id": "sample-rn-001",
                "license_number": "RN992100",
                "license_type_code": "RN",
                "profession": "Registered Nurse",
                "specialty": "Critical Care",
                "full_name": "Elena Brooks",
                "business_name": "Austin Regional Medical",
                "status_raw": "Active",
                "issue_date": today.replace(year=today.year - 6),
                "expiration_date": today + timedelta(days=45),
                "address_city": "Austin",
                "address_state": "TX",
                "address_zip": "78705",
                "source_fetched_at": datetime.now(timezone.utc),
            },
            {
                "source_state": "FL",
                "source_agency": "Florida DBPR",
                "source_url": "https://www.myfloridalicense.com/wl11.asp",
                "source_record_id": "sample-ec-001",
                "license_number": "EC13012001",
                "license_type_code": "EC",
                "profession": "Electrical Contractor",
                "specialty": "Commercial Electrical",
                "full_name": "Damon Patel",
                "business_name": "Patel Power Systems",
                "status_raw": "Current Active",
                "issue_date": today.replace(year=today.year - 9),
                "expiration_date": today + timedelta(days=12),
                "address_city": "Orlando",
                "address_state": "FL",
                "address_zip": "32801",
                "source_fetched_at": datetime.now(timezone.utc),
            },
            {
                "source_state": "CA",
                "source_agency": "Medical Board of California",
                "source_url": "https://search.dca.ca.gov/",
                "source_record_id": "sample-md-002",
                "license_number": "A120001",
                "license_type_code": "MD",
                "profession": "Physician",
                "specialty": "Orthopedics",
                "full_name": "Samuel Hart",
                "business_name": "Pacific Orthopedic Group",
                "status_raw": "Current",
                "issue_date": today.replace(year=today.year - 12),
                "expiration_date": today + timedelta(days=118),
                "address_city": "Los Angeles",
                "address_state": "CA",
                "address_zip": "90017",
                "source_fetched_at": datetime.now(timezone.utc),
            },
        ]
